/** Define ids for each page. */
export const PAGE_IDS = {
  ADMIN_PROFILE: 'admin-profile',
  ADD_STUFF: 'add-stuff',
  ADD_PROFILE: 'add-profile',
  ADD_ORGANIZATION: 'add-organization',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_FOUND: 'not-found',
  ORG_LIBRARY_PAGE: 'org-library-page',
  PROFILE_PAGE: 'profile-page',
  EDIT_PROFILE: 'edit-profile',
  SIGN_IN: 'sigin-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  ORGANIZATION_PROFILE: 'org-profile',
};
